from paths import (
    BEST_MODEL_PATH,
    FIGURES_DIR,
    LAST_MODEL_PATH,
    PROCESSED_DATASETS_PATH,
    RAW_DATASETS_PATH,
    STOPWORDS_PATH,
)

__all__ = [
    "FIGURES_DIR",
    "STOPWORDS_PATH",
    "RAW_DATASETS_PATH",
    "PROCESSED_DATASETS_PATH",
    "BEST_MODEL_PATH",
    "LAST_MODEL_PATH",
]
